"""
QuantAlpha Tier-Aware Formatter

Transforms raw daily_brief data into tier-specific outputs:
- Free: Limited to top 3 coins, basic scores, CTA for premium
- Premium: Full 20-coin matrix, whale alerts, RSI pullbacks, trade journal
- Institutional: Raw JSON feed, custom watchlists, historical archive
"""

import json
from datetime import datetime, timezone
from typing import Dict, List, Optional, Any

# ─── Tier Definitions ──────────────────────────────────────────────────────────

TIERS = {
    "free": {
        "name": "QuantAlpha Free",
        "max_coins": 3,
        "sections": [
            "executive_summary",
            "market_prices",
            "composite_scores",
            "cta_upgrade",
        ],
        "format": "discord_embed",
    },
    "premium": {
        "name": "QuantAlpha Premium",
        "max_coins": 20,
        "sections": [
            "executive_summary",
            "market_prices",
            "composite_scores",
            "whale_watch",
            "rsi_pullbacks",
            "featured_opportunities",
            "trade_journal",
            "risk_disclaimer",
        ],
        "format": "email_html",
    },
    "institutional": {
        "name": "QuantAlpha Institutional",
        "max_coins": None,  # Unlimited / custom watchlist
        "sections": "all",
        "format": "json_api",
    },
}

FREE_COINS = ["bitcoin", "ethereum", "solana"]


# ─── Formatters ─────────────────────────────────────────────────────────────────

def format_free_brief(report_data: Dict, coins: List[str] = None) -> str:
    """
    Generate free-tier brief for Discord.
    Top 3 coins only, basic scores, upgrade CTA.
    """
    if coins is None:
        coins = FREE_COINS
    
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%A, %B %d, %Y")
    
    lines = []
    lines.append(f"# 📊 QuantAlpha Daily Brief — Free Tier")
    lines.append(f"**{date_str}**")
    lines.append("")
    
    # Executive Summary — top 3 only
    scores = report_data.get("composite_scores", {})
    if scores:
        lines.append("## 🎯 Market Snapshot")
        count = 0
        for symbol, score_data in scores.items():
            if count >= 3:
                break
            if isinstance(score_data, dict):
                score = score_data.get("composite_score", 0)
                signal = score_data.get("signal", "N/A")
                emoji = _signal_emoji(signal)
                lines.append(f"- **{symbol}**: {emoji} {signal} — {score:.0f}/100")
            count += 1
        lines.append("")
    
    # Market Prices — top 3 only
    prices = report_data.get("prices", {})
    if prices:
        lines.append("## 💰 Prices")
        for coin_id in coins[:3]:
            price_data = prices.get(coin_id, {})
            if isinstance(price_data, dict) and price_data.get("usd"):
                price = price_data["usd"]
                change = price_data.get("usd_24h_change", 0)
                symbol = price_data.get("symbol", coin_id).upper()
                change_str = f"+{change:.1f}%" if change >= 0 else f"{change:.1f}%"
                lines.append(f"- **{symbol}**: ${price:,.2f} ({change_str})")
        lines.append("")
    
    # CTA — Upgrade prompt
    lines.append("---")
    lines.append("🔒 **Want the full picture?**")
    lines.append("Premium members get:")
    lines.append("- 📊 Full 20-coin signal matrix")
    lines.append("- 🐋 Real-time whale alerts")
    lines.append("- 📉 RSI pullback notifications")
    lines.append("- 📈 Trade journal transparency")
    lines.append("")
    lines.append("👉 **Upgrade to Premium ($29/mo)**: [Subscribe Now](https://particulatellc.com/quantalpha)")
    lines.append("")
    lines.append("⚠️ *Not financial advice. Signals for educational purposes only.*")
    lines.append("*Generated by Particulate LLC QuantAlpha v0.1*")
    
    return "\n".join(lines)


def format_premium_brief(report_data: Dict, coins: List[str] = None) -> str:
    """
    Generate premium-tier brief for email.
    Full 20-coin matrix, whale alerts, RSI pullbacks, trade journal.
    """
    if coins is None:
        coins = list(report_data.get("composite_scores", {}).keys())[:20]
    
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%A, %B %d, %Y")
    
    lines = []
    lines.append(f"# 📊 QuantAlpha Premium Brief")
    lines.append(f"**{date_str}** — *Premium Members Only*")
    lines.append("")
    
    # Full Signal Matrix
    scores = report_data.get("composite_scores", {})
    if scores:
        lines.append("## 🎯 Full Signal Matrix")
        lines.append("")
        lines.append("| Coin | Signal | Score | Confidence | RSI | Trend |")
        lines.append("|------|--------|-------|------------|-----|-------|")
        for symbol, sd in scores.items():
            if not isinstance(sd, dict):
                continue
            score = sd.get("composite_score", 0)
            signal = sd.get("signal", "N/A")
            confidence = sd.get("confidence", "N/A")
            rsi = sd.get("rsi", 0)
            ta = sd.get("ta_data", {})
            trend = ta.get("trend", "N/A") if isinstance(ta, dict) else "N/A"
            emoji = _signal_emoji(signal)
            lines.append(f"| **{symbol}** | {emoji} {signal} | {score:.0f} | {confidence} | {rsi:.0f} | {trend} |")
        lines.append("")
    
    # Whale Watch
    smart_money = report_data.get("smart_money", {})
    if smart_money and "error" not in smart_money:
        lines.append("## 🐋 Whale Watch")
        flows = smart_money.get("flows", smart_money.get("whale_flows", []))
        if isinstance(flows, list) and flows:
            for flow in flows[:5]:
                if isinstance(flow, dict):
                    wallet = flow.get("wallet", flow.get("label", "?"))[:16]
                    direction = flow.get("direction", flow.get("action", "?"))
                    amount = flow.get("amount_usd", flow.get("value", 0))
                    coin = flow.get("coin", flow.get("token", "?"))
                    emoji = "🟢" if "buy" in str(direction).lower() else "🔴"
                    lines.append(f"- {emoji} **{wallet}...** {direction} ${amount:,.0f} {coin}")
        else:
            lines.append("- No significant whale activity detected")
        lines.append("")
    
    # RSI Pullback Alerts
    lines.append("## 📉 RSI Pullback Alerts")
    pullbacks = _find_rsi_pullbacks(scores)
    if pullbacks:
        for pb in pullbacks:
            lines.append(f"- **{pb['symbol']}**: RSI {pb['rsi']:.0f} — {pb['signal']} ({pb['type']})")
    else:
        lines.append("- No RSI pullback alerts triggered")
    lines.append("")
    
    # Featured Opportunities
    lines.append("## ⭐ Featured Opportunities")
    opps = _find_opportunities(scores)
    if opps:
        for opp in opps[:3]:
            lines.append(f"- **{opp['symbol']}**: {opp['signal']} (Score {opp['score']:.0f}, {opp['reason']})")
    else:
        lines.append("- No high-conviction opportunities identified")
    lines.append("")
    
    # Trade Journal
    lines.append("## 📈 Trade Journal (Paper Trading)")
    lines.append("- *Performance data will appear after 7 days of tracking*")
    lines.append("")
    
    # Footer
    lines.append("---")
    lines.append("📊 **QuantAlpha Premium** — Particulate LLC")
    lines.append("Manage subscription: [Account Settings](https://particulatellc.com/quantalpha)")
    lines.append("")
    lines.append("⚠️ *Not financial advice. DYOR.*")
    
    return "\n".join(lines)


def format_institutional_feed(report_data: Dict, coins: List[str] = None) -> Dict:
    """
    Generate institutional-tier raw JSON signal feed.
    For API consumption and custom bot integration.
    """
    now = datetime.now(timezone.utc)
    
    feed = {
        "timestamp": now.isoformat(),
        "version": "0.1.0",
        "tier": "institutional",
        "signals": {},
        "alerts": [],
        "metadata": {
            "source": "Particulate LLC QuantAlpha",
            "coins_analyzed": len(report_data.get("composite_scores", {})),
        }
    }
    
    # Raw signal data
    scores = report_data.get("composite_scores", {})
    for symbol, sd in scores.items():
        if isinstance(sd, dict):
            feed["signals"][symbol] = {
                "composite_score": sd.get("composite_score", 0),
                "signal": sd.get("signal", "N/A"),
                "confidence": sd.get("confidence", "N/A"),
                "rsi": sd.get("rsi", 0),
                "ta_score": sd.get("ta_score", 0),
                "onchain_score": sd.get("onchain_score", 0),
                "smart_money_score": sd.get("smart_money_score", 0),
                "defi_score": sd.get("defi_score", 0),
                "social_score": sd.get("social_score", 0),
            }
    
    # Alerts
    pullbacks = _find_rsi_pullbacks(scores)
    for pb in pullbacks:
        feed["alerts"].append({
            "type": "rsi_pullback",
            "symbol": pb["symbol"],
            "rsi": pb["rsi"],
            "signal": pb["signal"],
            "timestamp": now.isoformat(),
        })
    
    # Whale alerts
    smart_money = report_data.get("smart_money", {})
    flows = smart_money.get("flows", smart_money.get("whale_flows", []))
    if isinstance(flows, list):
        for flow in flows[:10]:
            if isinstance(flow, dict):
                feed["alerts"].append({
                    "type": "whale_alert",
                    "wallet": flow.get("wallet", "?"),
                    "direction": flow.get("direction", "?"),
                    "amount_usd": flow.get("amount_usd", 0),
                    "coin": flow.get("coin", "?"),
                    "timestamp": now.isoformat(),
                })
    
    return feed


# ─── Helper Functions ────────────────────────────────────────────────────────────

def _signal_emoji(signal: str) -> str:
    s = str(signal).upper()
    if "BUY" in s and "STRONG" in s:
        return "🟢🟢"
    elif "BUY" in s:
        return "🟢"
    elif "SELL" in s and "STRONG" in s:
        return "🔴🔴"
    elif "SELL" in s:
        return "🔴"
    elif "NEUTRAL" in s:
        return "⚪"
    else:
        return "⚪"


def _find_rsi_pullbacks(scores: Dict) -> List[Dict]:
    """Find coins with RSI in pullback territory (oversold < 30 or overbought > 70)."""
    pullbacks = []
    for symbol, sd in scores.items():
        if not isinstance(sd, dict):
            continue
        rsi = sd.get("rsi", 50)
        try:
            rsi = float(rsi)
        except (TypeError, ValueError):
            continue
        
        if rsi < 30:
            pullbacks.append({
                "symbol": symbol,
                "rsi": rsi,
                "signal": "OVERSOLD — Potential bounce",
                "type": "bullish_pullback",
            })
        elif rsi > 70:
            pullbacks.append({
                "symbol": symbol,
                "rsi": rsi,
                "signal": "OVERBOUGHT — Potential pullback",
                "type": "bearish_pullback",
            })
    
    return pullbacks


def _find_opportunities(scores: Dict) -> List[Dict]:
    """Find high-conviction opportunities (BUY signal + score > 60 + confidence)."""
    opps = []
    for symbol, sd in scores.items():
        if not isinstance(sd, dict):
            continue
        score = sd.get("composite_score", 0)
        signal = str(sd.get("signal", "")).upper()
        confidence = sd.get("confidence", "low")
        
        try:
            score = float(score)
        except (TypeError, ValueError):
            continue
        
        if "BUY" in signal and score > 60:
            reason_parts = []
            if sd.get("defi_score", 0) > 70:
                reason_parts.append("strong DeFi")
            if sd.get("social_score", 0) > 70:
                reason_parts.append("positive sentiment")
            if sd.get("smart_money_score", 0) > 60:
                reason_parts.append("smart money inflow")
            
            opps.append({
                "symbol": symbol,
                "score": score,
                "signal": signal,
                "confidence": confidence,
                "reason": ", ".join(reason_parts) if reason_parts else "composite signal",
            })
    
    return sorted(opps, key=lambda x: x["score"], reverse=True)
